#开发配置
spring:
  datasource:
    url: jdbc:mysql://39.108.121.190:3306/test
    username: root
    password: 11235813a
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat

  #日志配置
#logging:
 # config: classpath:logback_config/logback-dev.xml
